#!/bin/bash

set -euo pipefail

PYTHON="${PYTHON:-.venv/bin/python}"
INDEX_URL="https://pypi.org/simple"

PROVENANCE="$("$PYTHON" -c 'import platform, sys; \
expected = sys.implementation.name == "cpython" and sys.version_info[:2] == (3, 13) and platform.system() == "Darwin"; \
expected or (_ for _ in ()).throw(SystemExit(f"Snapshots require macOS CPython 3.13; got {platform.system()} {platform.machine()} {sys.implementation.name} {sys.version.split()[0]}")); \
print(f"{platform.system()} {platform.machine()} CPython {sys.version_info.major}.{sys.version_info.minor}")')"
RUNTIME_TMP="$(mktemp requirements.txt.XXXXXX)"
DEV_TMP="$(mktemp requirements-dev.txt.XXXXXX)"

trap 'rm -f "$RUNTIME_TMP" "$DEV_TMP"' EXIT

# Bootstrap tools are intentionally outside the committed snapshots.
env -u PIP_NO_INDEX PIP_INDEX_URL="$INDEX_URL" "$PYTHON" -m pip install --upgrade -r requirements-bootstrap.txt
env -u PIP_NO_INDEX PIP_INDEX_URL="$INDEX_URL" "$PYTHON" -m pip install --upgrade "pip-tools>=7.4"

env -u PIP_NO_INDEX PIP_INDEX_URL="$INDEX_URL" "$PYTHON" -m piptools compile \
    --no-config --no-header --upgrade --resolver=backtracking --strip-extras \
    --index-url "$INDEX_URL" --constraint constraints.txt --output-file="$RUNTIME_TMP" pyproject.toml
env -u PIP_NO_INDEX PIP_INDEX_URL="$INDEX_URL" "$PYTHON" -m piptools compile \
    --no-config --no-header --upgrade --resolver=backtracking --strip-extras \
    --index-url "$INDEX_URL" --constraint constraints.txt --extra dev --output-file="$DEV_TMP" pyproject.toml

{
    printf '%s\n' "# This file is autogenerated by ./update_dependencies.sh on $PROVENANCE."
    printf '%s\n' '# It is a macOS CPython 3.13-specific resolved snapshot from pyproject.toml and constraints.txt.'
    printf '%s\n' '# requirements-bootstrap.txt pins pip==25.1.1 and setuptools==84.0.0 outside this snapshot.'
    printf '\n'
    command cat "$RUNTIME_TMP"
} > requirements.txt

{
    printf '%s\n' "# This file is autogenerated by ./update_dependencies.sh on $PROVENANCE."
    printf '%s\n' '# It is a macOS CPython 3.13-specific resolved snapshot from pyproject.toml and constraints.txt.'
    printf '%s\n' '# requirements-bootstrap.txt pins pip==25.1.1 and setuptools==84.0.0 outside this snapshot.'
    printf '\n'
    command cat "$DEV_TMP"
} > requirements-dev.txt
